### ISSUE TITLE
JIT for Rubex?

### ISSUE THREAD

**Issue by lokeshh** [v0dro/rubex#3]
Rubex complements Ruby. Is there a reason why it can't replace Ruby? Because wouldn't it be great if we can make it act like JIT (just in time) compile. This way we can retain advantage of interpreter and performance of compiler at same time.

**Comment by v0dro** [comment]
You're missing the point of Rubex. Its a language that compiles to C and interfaces with the CRuby interpreter using the CRuby C API. The purpose is to make it easier to write C extensions, something like Cython for Python.

**Comment by lokeshh** [comment]
Yeah I see it now. BTW I tried it with fibonnaci example. It is way faster and also easy to use! Finally I will be able to do competitive programming in Ruby. Cheers!
